config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: 'fishlists#index'
  resources :fishlists do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get :followings, :followers
    end
    member do
      get :favorites
    end
    resource :follows, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :fishlists, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }

  has_many :relationships, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :reverse_of_relationships, class_name: 'Follow', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.find_or_create_by(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationship = relationships.find_by(followed_id: user_id)
    relationship&.destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_update_path_for(resource)
    user_path(resource)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.with_attached_avatar.order(:id).page(params[:page]).per(5)
    @q = User.ransack(params[:q])
    @user = @q.result
  end

  def show
    @user = User.find(params[:id])
    @fishlists = @user.fishlists.page(params[:page]).per(9).order('updated_at DESC')
    @favorites = Favorite.where(user_id: @user.id).all
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings.order(:id).page(params[:page])
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers.order(:id).page(params[:page])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% users.each do |user| %>
    <table>
        <tbody>
            <tr>
                <td class="width_1"><%= user.name %></td>
                <td>
                    <% if user.avatar.attached? %>
                        <%= image_tag user.avatar,size: '50x50' %>
                    <% else %>
                        <%= image_tag "noimage.jpeg",size: '50x50' %>
                    <% end %>
                </td>
                <td><%= link_to t('views.common.show'), user %></td>
            </tr>
        </tbody>
    </table><br>
<% end %>

<%= link_to t('views.common.back'), users_path %>

app/views/users/followers.html.erb
<div class="m-4">
    <h2> <%= t('users.show.followers') %> </h2>
    <%= render partial: "follow", locals: {users: @users} %>
</div>

app/views/users/followings.html.erb
<div class="m-4">
    <h2> <%= t('users.show.followings') %> </h2>
    <%= render partial: "follow", locals: {users: @users} %>
</div>

app/views/users/index.html.erb
<div class="m-4">
    <h1><%= t('.user') %></h1>

    <!-- 検索窓 -->
    <%= search_form_for @q do |f| %>
        <%= f.search_field :name_cont %>
        <%= f.submit '検索' %>
    <% end %><br>

    <!-- 検索結果 -->
    <% if @users.present? %>
        <% @user.each do |user| %>
            <table>
                <tbody>
                    <tr>
                        <td class="width_1"><%= user.name %></td>
                        <td>
                            <% if user.avatar.attached? %>
                                <%= image_tag user.avatar,size: '50x50' %>
                            <% else %>
                                <%= image_tag "noimage.jpeg",size: '50x50' %>
                            <% end %>
                        </td>
                        <td><%= link_to t('views.common.show'), user %></td>
                    </tr>
                </tbody>
            </table><br>
        <% end %>
    <% end %>

    <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="m-4 text-center">
    <% if current_user == @user %>
        <h1><%= t('views.common.mypage') %></h1>
    <% end %>

    <%= @user.name %><br>

    <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar,size: '80x80' %>
    <% else %>
        <%= image_tag "noimage.jpeg",size: '80x80' %>
    <% end %><br>

    <% if @user.profile.present? %>
        <%= @user.profile %><br><br>
    <% end %>

    <%= t('.followings_count') %>
    <%= link_to @user.followings.count, followings_user_path(@user) %>
    <%= t('.followers_count') %>
    <%= link_to @user.followers.count, followers_user_path(@user) %><br>

    <% unless current_user == @user %>
        <% if current_user.following?(@user) %>
            <%= button_to t('.unfollow'), user_follows_path(@user), method: :delete %>
        <% else %>
            <%= button_to t('.follow'), user_follows_path(@user), method: :post %>
        <% end %>
    <% end %>
</div>

<div class="m-4 text-center">
    <h2>過去の投稿</h2>
    <div id="fishlists">
        <% if @fishlists.empty? %>
            まだ過去の投稿はありません<br>
        <% else %>
            <div class="row m-4">
                <div class="container">
                    <% @fishlists.each_slice(3) do |list_group| %>
                        <div class="row">
                            <% list_group.each do |fishlist| %>
                                <div class="col-md-4">
                                    <div class="border">
                                        <p><strong><%= t('views.common.date') %></strong><%= fishlist.date %></p>
                                        <p><strong><%= t('views.common.prefecture') %></strong><%= fishlist.prefecture.name %></p>
                                        <p><strong><%= t('views.common.place') %></strong><%= fishlist.place %></p>
                                        <p><strong><%= t('views.common.fishname') %></strong><%= fishlist.fishname %></p>
                                        <p><strong><%= t('views.common.fishingmethod') %></strong><%= fishlist.fishingmethod %></p>
                                        <p>
                                            <% if fishlist.fishimg.attached? %>
                                                <% fishlist.fishimg.each do |img| %>
                                                    <%= image_tag img,size: '100x100' %>
                                                <% end %>
                                            <% end %>
                                        </p>
                                        <p>
                                            <%= link_to t('views.common.show'), fishlist %>
                                        </p>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="m-4 text-center">
    <h2>いいねした投稿</h2>
    <div id="fishlists">
        <% if @favorites.exists? %>
            <div class="row m-4">
                <div class="container">
                    <% @favorites.each_slice(3) do |favorite_group| %>
                    <div class="row">
                        <% favorite_group.each do |favorite| %>
                        <% fishlist = favorite.fishlist %>
                        <div class="col-md-4">
                            <div class="border border_2 text-center">
                                <p><strong><%= t('views.common.creater') %></strong><%= link_to fishlist.user.name, user_path(fishlist.user.id) %></p>
                                <p><strong><%= t('views.common.date') %></strong><%= fishlist.date %></p>
                                <p><strong><%= t('views.common.prefecture') %></strong><%= fishlist.prefecture.name %></p>
                                <p><strong><%= t('views.common.place') %></strong><%= fishlist.place %></p>
                                <p><strong><%= t('views.common.fishname') %></strong><%= fishlist.fishname %></p>
                                <%= link_to t('views.common.show'), fishlist_path(fishlist.id) %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                    <% end %>
                </div>
            </div>
        <% else %>
                    いいねした投稿はまだありません<br>
        <% end %>
    </div>
</div>