config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: 'fishlists#index'
  resources :fishlists do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get :followings, :followers
    end
    member do
      get :favorites
    end
    resource :follows, only: [:create, :destroy]
  end
end

app/models/fishlist.rb
class Fishlist < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture

    has_many_attached :fishimg
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    validate :validate_image_count

    def validate_image_count
        if fishimg.attached? && fishimg.count > 6
            errors.add(:base, message: "写真は6枚まで添付できます")
        end
    end

    def self.ransackable_attributes(auth_object = nil)
        %w[date prefecture_name prefecture_id place fishname fishingmethod user_name]
    end

    def self.ransackable_associations(auth_object = nil)
        []
    end

    def favorited?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/controllers/fishlists_controller.rb
class FishlistsController < ApplicationController
  before_action :set_fishlist, only: %i[ show edit update destroy ]

  # GET /fishlists or /fishlists.json
  def index
    @fishlists = Fishlist.all.order(updated_at: :desc).page(params[:page]).per(3)
    @q = Fishlist.ransack(params[:q])
    @fishlist = @q.result.order(updated_at: :desc).page(params[:page]).per(3)
  end

  # GET /fishlists/1 or /fishlists/1.json
  def show
    @comment = Comment.new
    @comments = @fishlist.comments
    @likes_count = Favorite.where(fishlist_id: @fishlist.id).count
  end

  # GET /fishlists/new
  def new
    @fishlist = Fishlist.new
  end

  # GET /fishlists/1/edit
  def edit
  end

  # POST /fishlists or /fishlists.json
  def create
    @fishlist = Fishlist.new(fishlist_params)
    @fishlist.user_id = current_user.id

    respond_to do |format|
      if @fishlist.save
        format.html { redirect_to fishlist_url(@fishlist), notice: t('controllers.common.List_was_successfully_created') }
        format.json { render :show, status: :created, location: @fishlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fishlists/1 or /fishlists/1.json
  def update

    if params[:fishlist][:img_ids].present?
      params[:fishlist][:img_ids].each do |image_id|
        image = @fishlist.fishimg.find(image_id)
        image.purge
      end
    end

    respond_to do |format|
      if @fishlist.update(fishlist_params)
        format.html { redirect_to fishlist_url(@fishlist), notice: t('controllers.common.List_was_successfully_updated') }
        format.json { render :show, status: :ok, location: @fishlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fishlists/1 or /fishlists/1.json
  def destroy
    @fishlist.destroy

    respond_to do |format|
      format.html { redirect_to fishlists_url, notice: t('controllers.common.List_was_successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fishlist
      @fishlist = Fishlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fishlist_params
      params.require(:fishlist).permit(:date, :time, :maxtime, :weather, :prefecture_id, :place, :map, :fishname, :quantity, :fishlength, :maxfishlength, :fishweight, :maxfishweight,:fishingmethod, :message, fishimg: [])
    end
end

app/helpers/fishlists_helper.rb
module FishlistsHelper
end

app/views/fishlists/_fishlist.html.erb
<div id="<%= dom_id fishlist %>">

  <p>
    <strong><%= t('views.common.creater') %></strong>
    <%= link_to fishlist.user.name, user_path(fishlist.user.id) %>
  </p>

  <p>
    <strong><%= t('views.common.date') %></strong>
    <%= fishlist.date.strftime("%Y/%m/%d") %>
  </p>

  <p>
    <strong><%= t('views.common.time') %></strong>
    <% if fishlist.time.present? %>
      <%= fishlist.time.strftime("%H:%M") %>
    <% end %>
    <% if fishlist.maxtime.present? %>
      ～ <%= fishlist.maxtime.strftime("%H:%M") %>
    <% end %>
  </p>

  <p>
    <strong><%= t('views.common.weather') %></strong>
    <%= fishlist.weather %>
  </p>

  <p>
    <strong><%= t('views.common.prefecture') %></strong>
    <%= fishlist.prefecture.name %>
  </p>

  <p>
    <strong><%= t('views.common.place') %></strong>
    <%= fishlist.place %>
  </p>

  <p>
    <strong><%= t('views.common.fishname') %></strong>
    <%= fishlist.fishname %>
  </p>

  <p>
    <strong><%= t('views.common.quantity') %></strong>
    <%= fishlist.quantity %> 匹
  </p>

  <p>
    <strong><%= t('views.common.fishlength') %></strong>
    <% if fishlist.fishlength.present? %>
      <%= fishlist.fishlength %>
    <% end %>
    <% if fishlist.maxfishlength.present? %>
      ～ <%= fishlist.maxfishlength %>
    <% end %> cm
  </p>

  <p>
    <strong><%= t('views.common.fishweight') %></strong>
    <% if fishlist.fishweight.present? %>
      <%= fishlist.fishweight %>
    <% end %>
    <% if fishlist.maxfishweight.present? %>
      ～ <%= fishlist.maxfishweight %>
    <% end %> g
  </p>

  <p>
    <strong><%= t('views.common.fishingmethod') %></strong>
    <%= fishlist.fishingmethod %>
  </p>

  <p>
    <% if fishlist.fishimg.attached? %>
      <% fishlist.fishimg.each do |img| %>
        <%= image_tag img,size: '200x200' %>
      <% end %>
    <% end %>
  </p>

  <p>
    <strong><%= t('views.common.message') %></strong>
    <%= fishlist.message %>
  </p>

  <p class="font_s1">
    <%= t('views.common.created_date') %>
    <%= fishlist.created_at.to_fs(:datetime_jp) %>
  </p>

  <p class="font_s1">
    <%= t('views.common.update_date') %>
    <%= fishlist.updated_at.to_fs(:datetime_jp) %>
  </p>

</div>

app/views/fishlists/_form.html.erb
<div class="m-4">
    <%= form_with(model: fishlist) do |form| %>
    <% if fishlist.errors.any? %>
      <div class="red">
        <h2>保存できませんでした</h2>

        <ul>
          <% fishlist.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <strong><%= form.label t('views.common.date'), style: "display: block" %></strong>
      <%= form.date_field :date, data: { date_format: 'YYYY/MM/DD' } %>
    </div>

    <div>
      <strong><%= form.label t('views.common.time'), style: "display: block" %></strong>
      <%= form.time_field :time %> ～ <%= form.time_field :maxtime %>
    </div>

    <div>
      <strong><%= form.label t('views.common.weather'), style: "display: block" %></strong>
      <%= form.text_field :weather %>
    </div>

    <div>
      <strong><%= form.label t('views.common.prefecture'), style: "display: block" %></strong>
      <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name) %>
    </div>

    <div>
      <strong><%= form.label t('views.common.place'), style: "display: block" %></strong>
      <%= form.text_field :place %>
    </div>

    <div>
      <strong><%= form.label t('views.common.fishname'), style: "display: block" %></strong>
      <%= form.text_field :fishname %>
    </div>

    <div>
      <strong><%= form.label t('views.common.quantity'), style: "display: block" %></strong>
      <%= form.number_field :quantity, in: 0..999999 %> 匹
    </div>

    <div>
      <strong><%= form.label t('views.common.fishlength'), style: "display: block" %></strong>
      <%= form.number_field :fishlength, in: 0..999999 %> ～ <%= form.number_field :maxfishlength, in: 0..999999 %> cm
    </div>

    <div>
      <strong><%= form.label t('views.common.fishweight'), style: "display: block" %></strong>
      <%= form.number_field :fishweight, in: 0..999999 %> ～ <%= form.number_field :maxfishweight, in: 0..999999 %> g
    </div>

    <div>
      <strong><%= form.label t('views.common.fishingmethod'), style: "display: block" %></strong>
      <%= form.text_field :fishingmethod %>
    </div>

    <div>
        <% if fishlist.fishimg.attached? %>
        削除する画像に✓を付けてください<br>
            <% fishlist.fishimg.each do |img| %>
                  <%= form.check_box :img_ids, {:multiple => true}, img.id, false %>
                  <%= image_tag img,size: '50x50' %>
                <% end %><br>
            <% end %>
        <div class="red">最大６枚までアップできます<br></div>
        <%= form.file_field :fishimg, multiple: true %>
    </div><br>

    <div>
      <strong><%= form.label t('views.common.message'), style: "display: block" %></strong>
      <%= form.text_area :message %>
    </div>

    <div>
      <%= form.submit %>
    </div>
    <% end %>

</div>

app/views/fishlists/edit.html.erb
<div class="m-4">
  <h1><%= t('views.common.edit') %></h1>

  <%= render "form", fishlist: @fishlist %>

  <div>
    <%= link_to t('views.common.show'), @fishlist %> |
    <%= link_to t('views.common.back'), fishlists_path %>
  </div>

</div>

app/views/fishlists/index.html.erb
<div class="text-center">
  <div class="font_s2"><%= link_to t('views.common.new'), new_fishlist_path %></div>
  <div class="font_s2 font_bold"><%= t('views.common.newpost') %></div>

  <!-- 検索窓 -->
  <%= search_form_for @q, url: fishlists_path do |f| %>
  <div style= "display: inline-block;">
    <%= f.label :date_cont, '日付' %>
      <%= f.date_field :date_cont, class: "form-control", style: "width:200px" %>
  </div>
  <div style= "display: inline-block;">
    <%= f.label :prefecture_name, '都道府県' %><br>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: ' '}, class: 'form-control' %>
  </div>
  <div style= "display: inline-block;">
    <%= f.label :place_cont, '場所' %>
      <%= f.search_field :place_cont, placeholder:"例：〇〇湖", class: "form-control", style: "width:200px" %>
  </div>
  <div style= "display: inline-block;">
    <%= f.label :fishname_cont, '魚の種類' %>
      <%= f.search_field :fishname_cont, placeholder:"例：ブリ", class: "form-control", style: "width:200px" %>
  </div>
  <div style= "display: inline-block;">
    <%= f.label :fishingmethod_cont, '釣り方' %>
      <%= f.search_field :fishingmethod_cont, placeholder:"例：ルアー", class: "form-control", style: "width:200px" %>
  </div>
      <%= f.submit '検索' %>
  <% end %>
  </div>
</div>

<div class="row m-4">
  <div class="container">
    <% if @fishlist.present? %>
      <% @fishlist.each_slice(3) do |list_group| %>
        <div class="row">
          <% list_group.each do |list| %>
            <div class="col-md-4">
              <div class="border">
                <p>
                  <strong><%= t('views.common.creater') %></strong>
                  <%= link_to list.user.name, user_path(list.user.id) %>
                </p>
                <p>
                  <strong><%= t('views.common.date') %></strong>
                  <%= list.date.strftime('%Y/%m/%d') %>
                </p>
                <p>
                  <strong><%= t('views.common.prefecture') %></strong>
                  <%= list.prefecture.name %>
                </p>
                <p>
                  <strong><%= t('views.common.place') %></strong>
                  <%= list.place %>
                </p>
                <p>
                  <strong><%= t('views.common.fishname') %></strong>
                  <%= list.fishname %>
                </p>
                <p>
                  <strong><%= t('views.common.fishingmethod') %></strong>
                  <%= list.fishingmethod %>
                </p>
                <p>
                  <% if list.fishimg.attached? %>
                    <% list.fishimg.each do |img| %>
                      <%= image_tag img, size: '100x100' %>
                    <% end %>
                  <% end %>
                </p>
                <p>
                  <%= link_to t('views.common.show'), list %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p style="text-align:center">該当するデータはありません</p>
    <% end %>
  </div>
</div>

<%= paginate @fishlist %>

app/views/fishlists/new.html.erb
<div class="m-4">
  <h1><%= t('views.common.new') %></h1>

  <%= render "form", fishlist: @fishlist %>

  <%= link_to t('views.common.back'), fishlists_path %>

</div>

app/views/fishlists/show.html.erb
<div class="m-4">
  <%= render @fishlist %>

<% if @fishlist.user.id == current_user.id %>
  <%= link_to t('views.common.edit'), edit_fishlist_path(@fishlist) %>
  <%= button_to t('views.common.destroy'), @fishlist, method: :delete %>
<% end %>

  <% if @fishlist.favorited?(current_user) %>
    <%= button_to fishlist_favorite_path(@fishlist), method: :delete, class: "button" do %>
      <div class="container">
        <div class="heart_red" title="いいねを取り消す" ><span class="heart_count"><%= @likes_count %></span></div>
      </div>
    <% end %>
  <% else %>
    <%= button_to fishlist_favorites_path(@fishlist), method: :post, class: "button" do %>
      <div class="container">
        <div class="heart_gray" title="いいねする" ><span class="heart_count"><%= @likes_count %></span></div>
      </div>
    <% end %>
  <% end %><br>

  <div>

  <div class="font_s3">💬コメント</div>
  <%= form_with model: [@fishlist, @comment], method: :fishlist do |f| %>
    <%= f.text_area :comment_content %>
    <%= f.submit '投稿' %>
  <% end %>

  <% if @comments.empty? %>
      コメントはまだありません<br>
  <% else %>
    <% @comments.each do |c| %>
      <strong><%= link_to c.user.name, user_path(c.user.id) %></strong> さん：
      <%= c.comment_content %>
        <% if c.user_id == current_user.id %>
          <div style= "display: inline-block;">
            <div style="margin: 5px;">
              <%= button_to '削除', fishlist_comment_path(@fishlist, c), method: :delete %>
            </div>
          </div>
        <% end %><br>
    <% end %>
  <% end %>

    <%= link_to t('views.common.user_fishlist_back'), user_path(@fishlist.user.id) %>
  </div>
</div>